CREATE DATABASE Proyecto_Final;
USE Proyecto_Final;

CREATE TABLE CATEGORIAS
(ID_CATEGORIA INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
NOMBRE VARCHAR(45) NOT NULL,
DESCRIPCION VARCHAR(200)
);

INSERT INTO `CATEGORIAS` (`ID_CATEGORIA`,`NOMBRE`,`DESCRIPCION`) values (1, 'Verduras', 'Todo tipo de verduras y hortalizas');
INSERT INTO `CATEGORIAS` (`ID_CATEGORIA`,`NOMBRE`,`DESCRIPCION`) values (2, 'Fruta', 'Tipos de fruta de todo el mundo');
INSERT INTO `CATEGORIAS` (`ID_CATEGORIA`,`NOMBRE`,`DESCRIPCION`) values (3, 'Productos Varios', 'Productos varios de Km0');


CREATE TABLE PRODUCTOS
(ID_PRODUCTO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
NOMBRE VARCHAR(50) NOT NULL,
DESCRIPCION VARCHAR(200),
IMAGEN VARCHAR(200),
ESTADO VARCHAR(20),
VALORACION VARCHAR(200),
PRECIO DEC(9,2),
ID_CATEGORIA INT NOT NULL,
FOREIGN KEY(ID_CATEGORIA) REFERENCES CATEGORIAS(ID_CATEGORIA)
);

CREATE TABLE USUARIOS
(
USERNAME VARCHAR(45) NOT NULL PRIMARY KEY,
PASSWORD VARCHAR(200) NOT NULL,
NOMBRE VARCHAR(50),
PRIMER_APELLIDO VARCHAR(50),
SEGUNDO_APELLIDO VARCHAR(50),
POBLACION VARCHAR(100),
CALLE VARCHAR(100),
NUMERO VARCHAR(100),
CP INT,
EMAIL VARCHAR(100),
FOTO VARCHAR(200),
ENABLED VARCHAR(50) NOT NULL DEFAULT 'activo',
FECHA_REGISTRO DATE
);


INSERT INTO `USUARIOS` (`USERNAME`,`PASSWORD`,`NOMBRE`,`PRIMER_APELLIDO`,`SEGUNDO_APELLIDO`,`POBLACION`,`CALLE`,`NUMERO`,`CP`,`EMAIL`,`FOTO`,`ENABLED`,`FECHA_REGISTRO`) VALUES ('Geri','{noop}geri','Gerard','Perujo','Buxeda','Puigcerda','Mont-cerda','nº1 bajo 1',17520,'ger.pe85@gmail.com','null','activo','2024-03-14');
INSERT INTO `USUARIOS` (`USERNAME`,`PASSWORD`,`NOMBRE`,`PRIMER_APELLIDO`,`SEGUNDO_APELLIDO`,`POBLACION`,`CALLE`,`NUMERO`,`CP`,`EMAIL`,`FOTO`,`ENABLED`,`FECHA_REGISTRO`) VALUES ('Mari','{noop}mari','Maria','Isabel','Martín','Madrid','Avenida FelipeVI','nº300 segundo 3',28001,'mar.Isab@gmail.com','null','activo','2024-03-14');
INSERT INTO `USUARIOS` (`USERNAME`,`PASSWORD`,`NOMBRE`,`PRIMER_APELLIDO`,`SEGUNDO_APELLIDO`,`POBLACION`,`CALLE`,`NUMERO`,`CP`,`EMAIL`,`FOTO`,`ENABLED`,`FECHA_REGISTRO`) VALUES ('Noeli','{noop}noeli','Noelia','Villahermosa','Garcia','Ciudad Real','Avenida España','nº200 quarto 3',13001,'noe.villa@gmail.com','null','activo','2024-03-14');


CREATE TABLE COMPRAS
(ID_COMPRA INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
ID_PRODUCTO INT NOT NULL,
USERNAME VARCHAR(45) NOT NULL,
PRECIO_VENTA DEC(9,2),
CANTIDAD INT,
FOREIGN KEY(USERNAME) REFERENCES USUARIOS(USERNAME),
FOREIGN KEY(ID_PRODUCTO) REFERENCES PRODUCTOS(ID_PRODUCTO)
);

CREATE TABLE PEDIDOS
(ID_PEDIDO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
USERNAME VARCHAR(45),
FECHA_PEDIDO DATE,
PRECIO_TOTAL DEC(9,2),
FOREIGN KEY(USERNAME) REFERENCES USUARIOS(USERNAME)
);

CREATE TABLE COMPRAS_PEDIDOS
(ID_COMPRAS_PEDIDOS INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
ID_PEDIDO INT NOT NULL,
ID_COMPRA INT NOT NULL,
FOREIGN KEY(ID_PEDIDO) REFERENCES PEDIDOS(ID_PEDIDO),
FOREIGN KEY (ID_COMPRA) REFERENCES COMPRAS(ID_COMPRA));

-- TABLAS PARA LOGIN, LOGOUT y REGISTRO o  SPRING SECURITY 

CREATE TABLE PERFILES
(ID_PERFIL INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
NOMBRE VARCHAR(45) NOT NULL
);
INSERT INTO `PERFILES` (`ID_PERFIL`,`NOMBRE`) VALUES (1,'ROLE_ADMINISTRADOR');
INSERT INTO `PERFILES` (`ID_PERFIL`,`NOMBRE`) VALUES (2,'ROLE_GESTOR');
INSERT INTO `PERFILES` (`ID_PERFIL`,`NOMBRE`) VALUES (3,'ROLE_CLIENTE');

CREATE TABLE USUARIO_PERFILES
(USERNAME VARCHAR(45) NOT NULL,
ID_PERFIL INT NOT NULL,
PRIMARY KEY(USERNAME, ID_PERFIL),
FOREIGN KEY(USERNAME) REFERENCES USUARIOS(USERNAME),
FOREIGN KEY(ID_PERFIL) REFERENCES PERFILES(ID_PERFIL)
);

INSERT INTO `USUARIO_PERFILES` (`USERNAME`,`ID_PERFIL`) VALUES ('Geri',1);
INSERT INTO `USUARIO_PERFILES` (`USERNAME`,`ID_PERFIL`) VALUES ('Mari',1);
INSERT INTO `USUARIO_PERFILES` (`USERNAME`,`ID_PERFIL`) VALUES ('Noeli',1);




